
f = figure();

%Ticker 1
btn = uicontrol('Style', 'radiobutton', 'String', 'Market Making',...
    'Position', [20 300 100 30]);   
text_ticker1 = uicontrol('Style','text',...
                'Position', [10, 380, 100, 30],...
                'String', 'First Ticker');                
tickerOneName = uicontrol('Style', 'edit',...
                'Position', [10, 350, 80, 20]);
tickerOneOnOff = uicontrol('Style', 'radiobutton', 'String', 'ON/OFF',...
    'Position', [20 310 100 30]);
tickerOneMM = uicontrol('Style', 'radiobutton', 'String', 'Market Making',...
    'Position', [20 285 100 30]);  
tickerOneUnload = uicontrol('Style', 'radiobutton', 'String', 'Unloading',...
    'Position', [20 255 100 30]);    


% Ticker 2
textTicker2 = uicontrol('Style','text',...
                'Position', [150, 380, 100, 30],...
                'String', 'Second Ticker');       
tickerTwoName = uicontrol('Style', 'edit',...
                'Position', [150, 350, 80, 20]);
tickerTwoOnOff = uicontrol('Style', 'radiobutton', 'String', 'ON/OFF',...
    'Position', [150 310 100 30]);
tickerTwoMM = uicontrol('Style', 'radiobutton', 'String', 'Market Making',...
    'Position', [150 285 100 30]);  
tickerTwoUnload = uicontrol('Style', 'radiobutton', 'String', 'Unloading',...
    'Position', [150 255 100 30]); 

% Ticker 3
textTicker3 = uicontrol('Style','text',...
                'Position', [270, 380, 100, 30],...
                'String', 'Third Ticker');
tickerThreeName = uicontrol('Style', 'edit',...
                'Position', [290, 350, 80, 20]);
tickerThreeOnOff = uicontrol('Style', 'radiobutton', 'String', 'ON/OFF',...
    'Position', [290 310 100 30]);
tickerThreeMM = uicontrol('Style', 'radiobutton', 'String', 'Market Making',...
    'Position', [290 285 100 30]);  
tickerThreeUnload = uicontrol('Style', 'radiobutton', 'String', 'Unloading',...
    'Position', [290 255 100 30]); 


% Ticker 4
textTicker4 = uicontrol('Style','text',...
            'Position', [405, 380, 100, 30],...
            'String', 'Fourth Ticker');
tickerFourName = uicontrol('Style', 'edit',...
                'Position', [420, 350, 80, 20]);
tickerFourOnOff = uicontrol('Style', 'radiobutton', 'String', 'ON/OFF',...
    'Position', [420 310 100 30]);
tickerFourMM = uicontrol('Style', 'radiobutton', 'String', 'Market Making',...
    'Position', [420 285 100 30]);  
tickerFourUnload = uicontrol('Style', 'radiobutton', 'String', 'Unloading',...
    'Position', [420 255 100 30]); 

